# https://github.com/paperless-ngx/paperless-ngx/blob/dev/Dockerfile
FROM ghcr.io/paperless-ngx/paperless-ngx:latest

RUN set -x \
    && python3 -m pip install --no-cache django_yunohost_integration
