#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#-------------------------------------------------
# config_panel.toml settings:

if [ -z "$debug_enabled" ]; then
	debug_enabled="0"
	ynh_app_setting_set --app=$app --key=debug_enabled --value="$debug_enabled"
fi

if [ -z "$log_level" ]; then
	log_level="WARNING"
	ynh_app_setting_set --app=$app --key=log_level --value="$log_level"
fi

if [ -z "$admin_email" ]; then
	admin_email="${admin}@${domain}"
    ynh_app_setting_set --app=$app --key=admin_email --value="$admin_email"
fi

if [ -z "$default_from_email" ]; then
	default_from_email="${app}@${domain}"
	ynh_app_setting_set --app=$app --key=default_from_email --value="$default_from_email"
fi

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping systemd service '$app'..." --weight=5

ynh_systemd_action --service_name=$app --action="stop"


#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring systemd service '$app'..." --weight=5

ynh_add_systemd_config --service=$app --template="systemd.service"

#=================================================
# copy config files
# ================================================
ynh_script_progression --message="Create project configuration files..."
myynh_add_conf_files

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_script_progression --message="Set file permissions..."
myynh_fix_file_permissions

ynh_script_progression --message="Build '$app' docker images..." --weight=20
myynh_setup_docker

#=================================================
# Start the app server via systemd
#=================================================
ynh_script_progression --message="Starting systemd service '$app'..." --weight=5

yunohost service add $app --description="$app"
ynh_systemd_action --service_name=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
